global using System;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using Microsoft.EntityFrameworkCore;
global using System.Collections.Generic;
global using NetTopologySuite.Geometries;
global using IntroToEntityFrameworkCore.Data.Entities;
global using IntroToEntityFrameworkCore.Data.Enums;
